### ISSUE TITLE
Demo 里面的代码用不了

### ISSUE THREAD

**Issue by playniuniu** [panjjo/unionpay#1]
Hi

我看到您这边关于 unionpay 的 golang 实现，但是在使用的时候，直接复制 README 里面的代码，

没有 CertPathInfo 这个 Struct，也没有 apiconfig 这个变量

请教一下，能贴出完整的 Golang 实现的 Demo 吗？

**Comment by panjjo** [comment]
后来改了逻辑,忘了改readme
